# Generated by Django 5.2.17 on 2026-10-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "require_approval",
                    models.BooleanField(
                        default=False,
                        help_text="On pannina, pudhu users ah admin approve pannina dhaan login panna mudiyum",
                    ),
                ),
                (
                    "announcement",
                    models.CharField(
                        blank=True,
                        help_text="Home page la ellarukkum theriyura banner message",
                        max_length=300,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "site settings",
            },
        ),
    ]
