# Generated by Django 5.2.17 on 2026-10-02 17:13

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_sitesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True, upload_to=accounts.models.upload_avatar
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_preset",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="profile",
            name="birth_year",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="city",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="profile",
            name="cover",
            field=models.ImageField(blank=True, upload_to=accounts.models.upload_cover),
        ),
        migrations.AddField(
            model_name="profile",
            name="full_name",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("female", "Female"),
                    ("male", "Male"),
                    ("other", "Other"),
                    ("", "Prefer not to say"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="interests",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="profile",
            name="languages",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="profile",
            name="state",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
