# Generated by Django 5.2.17 on 2026-10-02 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0003_like_emoji_notification_extra_story_is_featured_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("emoji", models.CharField(default="🏆", max_length=8)),
                ("description", models.CharField(blank=True, max_length=400)),
                (
                    "content_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("kadhai", "Kadhai / Story"),
                            ("kavithai", "Kavithai / Poem"),
                            ("dialogue", "Dialogue"),
                            ("personal", "Personal story"),
                            ("article", "Article / Blog"),
                            ("quote", "Quote"),
                        ],
                        max_length=10,
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-starts_at"],
            },
        ),
        migrations.AddField(
            model_name="part",
            name="image",
            field=models.ImageField(blank=True, upload_to="part_images/"),
        ),
        migrations.AddField(
            model_name="part",
            name="speaker",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="story",
            name="chapter",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="story",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("kadhai", "Kadhai / Story"),
                    ("kavithai", "Kavithai / Poem"),
                    ("dialogue", "Dialogue"),
                    ("personal", "Personal story"),
                    ("article", "Article / Blog"),
                    ("quote", "Quote"),
                ],
                default="kadhai",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="cover",
            field=models.ImageField(blank=True, upload_to="story_covers/"),
        ),
        migrations.AddField(
            model_name="story",
            name="is_anonymous",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="story",
            name="is_winner",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="story",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="story",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="published",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="content",
            field=models.TextField(max_length=12000),
        ),
        migrations.AlterField(
            model_name="story",
            name="genre",
            field=models.CharField(
                choices=[
                    ("horror", "Horror"),
                    ("comedy", "Comedy"),
                    ("love", "Love"),
                    ("thriller", "Thriller"),
                    ("scifi", "Sci-Fi"),
                    ("drama", "Drama"),
                    ("life", "Life"),
                    ("family", "Family"),
                    ("friendship", "Friendship"),
                    ("motivation", "Motivation"),
                    ("nature", "Nature"),
                    ("mystery", "Mystery"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="challenge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entries",
                to="stories.challenge",
            ),
        ),
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="series",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "series",
            },
        ),
        migrations.AddField(
            model_name="story",
            name="series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chapters",
                to="stories.series",
            ),
        ),
    ]
